# Create Descriptors for Molecules

In [1]:
%pylab inline
%load_ext autoreload
%autoreload 2

Populating the interactive namespace from numpy and matplotlib


In [2]:
tmp_smile = 'CC1CC(C(C(C=C(C(C(C=CC=C(C(=O)NC2=CC(=O)C(=C(C1)C2=O)NCC=C)C)OC)OC(=O)N)C)C)O)OC'

### 2D RDKIT

In [3]:
from rdkit import Chem
from rdkit.Chem import Descriptors
from rdkit.ML.Descriptors import MoleculeDescriptors

def get_rdkit_descriptors(input_smile):
    calc = MoleculeDescriptors.MolecularDescriptorCalculator([x[0] for x in Descriptors._descList])
    mol = Chem.MolFromSmiles(input_smile)
    ds = calc.CalcDescriptors(mol)
    features = list(ds)
    feature_names = list(calc.GetDescriptorNames())
    return np.array(features,dtype=np.float32), feature_names    

In [4]:
get_rdkit_descriptors(tmp_smile)

(array([ 1.35437775e+01, -1.00060427e+00,  1.35437775e+01,  1.31979093e-01,
         2.70594180e-01,  5.85697998e+02,  5.42354004e+02,  5.85304993e+02,
         2.30000000e+02,  0.00000000e+00,  4.04704005e-01, -4.38726693e-01,
         4.38726693e-01,  4.04704005e-01,  1.21428573e+00,  1.90476191e+00,
         2.50000000e+00,  1.65777874e+01,  9.84752178e+00,  2.32994890e+00,
        -2.29647946e+00,  2.28428364e+00, -2.37488079e+00,  6.23184729e+00,
        -1.19791485e-01,  2.62030768e+00,  1.21242590e+03,  3.15597496e+01,
         2.51389332e+01,  2.51389332e+01,  1.98350449e+01,  1.37708559e+01,
         1.37708559e+01,  1.06005707e+01,  1.06005707e+01,  7.21674061e+00,
         7.21674061e+00,  4.95271158e+00,  4.95271158e+00, -3.79999995e+00,
         6.52578368e+08,  3.44014778e+01,  1.59985981e+01,  9.10164070e+00,
         2.46758804e+02,  3.56843605e+01,  6.10396624e+00,  6.10396624e+00,
         1.15664902e+01,  5.90717983e+00,  6.09324026e+00,  1.43836117e+01,
         4.7

### MACCS

In [5]:
from rdkit import Chem
from rdkit.Chem import MACCSkeys

def get_maccs(input_smile):
    MACCS_list = []
    mol = Chem.MolFromSmiles(input_smile)
    header = ['maccs_bit' + str(i) for i in range(167)]
    MACCS_list = list(MACCSkeys.GenMACCSKeys(mol).ToBitString())       
    return np.array(MACCS_list,dtype=np.float32), header

In [6]:
get_maccs(tmp_smile)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
        0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0.,
        0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0.,
        0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
        1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0.],
       dtype=float32),
 ['maccs_bit0',
  'maccs_bit1',
  'maccs_bit2',
  'maccs_bit3',
  'maccs_bit4',
  'maccs_bit5',
  'maccs_bit6',
  'maccs_bit7',
  'maccs_bit8',
  'maccs_bit9',
  'maccs_bit10',
  'maccs_bit11',
  'maccs_bit12',
  'maccs_bit13',


### ECFP6

In [7]:
from rdkit.Chem import AllChem
from rdkit import Chem, DataStructs

def mol2fp(mol, radius = 3):
    fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius = radius)
    array = np.zeros((1,))
    DataStructs.ConvertToNumpyArray(fp, array)
    return array

def get_ECFP6(input_smile):
    bit_headers = ['ecfp6_bit' + str(i) for i in range(2048)]
    arr = np.empty((0,2048), int).astype(int)
    mol = Chem.MolFromSmiles(input_smile)
    fp = mol2fp(mol)
    return np.array(list(fp),np.float32), bit_headers

In [8]:
get_ECFP6(tmp_smile)

(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 ['ecfp6_bit0',
  'ecfp6_bit1',
  'ecfp6_bit2',
  'ecfp6_bit3',
  'ecfp6_bit4',
  'ecfp6_bit5',
  'ecfp6_bit6',
  'ecfp6_bit7',
  'ecfp6_bit8',
  'ecfp6_bit9',
  'ecfp6_bit10',
  'ecfp6_bit11',
  'ecfp6_bit12',
  'ecfp6_bit13',
  'ecfp6_bit14',
  'ecfp6_bit15',
  'ecfp6_bit16',
  'ecfp6_bit17',
  'ecfp6_bit18',
  'ecfp6_bit19',
  'ecfp6_bit20',
  'ecfp6_bit21',
  'ecfp6_bit22',
  'ecfp6_bit23',
  'ecfp6_bit24',
  'ecfp6_bit25',
  'ecfp6_bit26',
  'ecfp6_bit27',
  'ecfp6_bit28',
  'ecfp6_bit29',
  'ecfp6_bit30',
  'ecfp6_bit31',
  'ecfp6_bit32',
  'ecfp6_bit33',
  'ecfp6_bit34',
  'ecfp6_bit35',
  'ecfp6_bit36',
  'ecfp6_bit37',
  'ecfp6_bit38',
  'ecfp6_bit39',
  'ecfp6_bit40',
  'ecfp6_bit41',
  'ecfp6_bit42',
  'ecfp6_bit43',
  'ecfp6_bit44',
  'ecfp6_bit45',
  'ecfp6_bit46',
  'ecfp6_bit47',
  'ecfp6_bit48',
  'ecfp6_bit49',
  'ecfp6_bit50',
  'ecfp6_bit51',
  'ecfp6_bit52',
  'ecfp6_bit53',
  'ecfp6_bit54',
  'ecfp6_bit55',
  'e

### Mordred MRC desriptors

In [9]:
from rdkit import Chem
from mordred import Calculator, descriptors
from mordred.RingCount import RingCount
import itertools

def compute_ringsize(mol):
    '''
    check for macrolides of RS 3 to 100, return a  list of ring counts.
    [RS3,RS4,.....,RS100]
    [0,0,0,...,1,...,0]
    '''
    RS_3_100 = [i+3 for i in range(97)]
    RS_count = []
    for j in RS_3_100:
        RS = RingCount(order=j)(mol)
        RS_count.append(RS)
    return RS_count

def macrolide_ring_info(mol):
    headers = ['n'+str(i+13)+'Ring' for i in range(87)]+['SmallestRS','LargestRS']
    # up to nR12 is already with mordred, start with nR13 to nR100
    ring_size = []
    RS = compute_ringsize(mol)  # nR3 to nR100
    RS_12_100 = RS[9:]    # start with nR12 up to nR100
    ring_indices = [i for i,x in enumerate(RS_12_100) if x!=0]  # get index if item isn't equal to 0
    if ring_indices:
        # find 1, locate the last index
        # largest_RS is based on RS 3 to 100.
        # Add 3 (starting ring count) to get up to the actual ring size
        smallest_RS = ring_indices[0]+12
        largest_RS = ring_indices[-1]+12
        RS_12_100.append(smallest_RS)  # Smallest RS
        RS_12_100.append(largest_RS)  # Largest RS
    else:
        RS_12_100.extend([0,0])
    ring_size = (RS_12_100[1:]) # up to nR12 is already with mordred, start with nR13 to nR100
    return np.array(ring_size, dtype=np.float32), headers


def sugar_count(mol):
    sugar_patterns = [
    '[OX2;$([r5]1@C@C@C(O)@C1),$([r6]1@C@C@C(O)@C(O)@C1)]',
    '[OX2;$([r5]1@C(!@[OX2,NX3,SX2,FX1,ClX1,BrX1,IX1])@C@C@C1),$([r6]1@C(!@[OX2,NX3,SX2,FX1,ClX1,BrX1,IX1])@C@C@C@C1)]',
    '[OX2;$([r5]1@C(!@[OX2,NX3,SX2,FX1,ClX1,BrX1,IX1])@C@C(O)@C1),$([r6]1@C(!@[OX2,NX3,SX2,FX1,ClX1,BrX1,IX1])@C@C(O)@C(O)@C1)]',
    '[OX2;$([r5]1@C(!@[OX2H1])@C@C@C1),$([r6]1@C(!@[OX2H1])@C@C@C@C1)]',
    '[OX2;$([r5]1@[C@@](!@[OX2,NX3,SX2,FX1,ClX1,BrX1,IX1])@C@C@C1),$([r6]1@[C@@](!@[OX2,NX3,SX2,FX1,ClX1,BrX1,IX1])@C@C@C@C1)]',
    '[OX2;$([r5]1@[C@](!@[OX2,NX3,SX2,FX1,ClX1,BrX1,IX1])@C@C@C1),$([r6]1@[C@](!@[OX2,NX3,SX2,FX1,ClX1,BrX1,IX1])@C@C@C@C1)]',
    ]
    sugar_mols = [Chem.MolFromSmarts(i) for i in sugar_patterns]
    sugar_counts = []
    matches_total = []
    for s_mol in sugar_mols:
        raw_matches = mol.GetSubstructMatches(s_mol)
        matches = np.sum(raw_matches)
        if matches not in matches_total and matches > 0:
            matches_total.append([matches])
    sugar_indices = set((list(itertools.chain(*matches_total))))
    count = len(sugar_indices)
    sugar_counts = count
    
    
    
    return np.array([sugar_counts],dtype=np.float32), ['nSugars']


def core_ester_count(mol):
    '''
    Returns pandas frame containing the count of esters in core rings of >=12 membered macrocycles.
    '''
    ester_smarts = '[CX3](=[OX1])O@[r;!r3;!r4;!r5;!r6;!r7;!r8;!r9;!r10;!r11]'
    core_ester = []
    ester_mol = Chem.MolFromSmarts(ester_smarts)
    ester_count = len(mol.GetSubstructMatches(ester_mol))
    core_ester = ester_count
    return np.array([core_ester],dtype=np.float32), ['core_ester']

def mordred_compute(mol):
    calc = Calculator(descriptors, ignore_3D=True)
    ds = calc.pandas([mol],quiet=True) 
    features = list(ds.values)
    feature_names = list(ds.keys())
    return np.array(features,dtype=np.float32).flatten(), feature_names

def get_mordred(input_smile):
    mol = Chem.MolFromSmiles(input_smile)
    features, feature_names = macrolide_ring_info(mol)
    
    tmp_features, tmp_feature_names = mordred_compute(mol)
    features = np.concatenate([features,tmp_features])
    feature_names += tmp_feature_names
    
    tmp_features, tmp_feature_names = sugar_count(mol)
    features = np.concatenate([features,tmp_features])
    feature_names += tmp_feature_names
    
    tmp_features, tmp_feature_names = core_ester_count(mol)
    features = np.concatenate([features,tmp_features])
    feature_names += tmp_feature_names
    return features, feature_names    

In [10]:
get_mordred(tmp_smile)

(array([0.      , 0.      , 0.      , ..., 9.666667, 0.      , 0.      ],
       dtype=float32),
 ['n13Ring',
  'n14Ring',
  'n15Ring',
  'n16Ring',
  'n17Ring',
  'n18Ring',
  'n19Ring',
  'n20Ring',
  'n21Ring',
  'n22Ring',
  'n23Ring',
  'n24Ring',
  'n25Ring',
  'n26Ring',
  'n27Ring',
  'n28Ring',
  'n29Ring',
  'n30Ring',
  'n31Ring',
  'n32Ring',
  'n33Ring',
  'n34Ring',
  'n35Ring',
  'n36Ring',
  'n37Ring',
  'n38Ring',
  'n39Ring',
  'n40Ring',
  'n41Ring',
  'n42Ring',
  'n43Ring',
  'n44Ring',
  'n45Ring',
  'n46Ring',
  'n47Ring',
  'n48Ring',
  'n49Ring',
  'n50Ring',
  'n51Ring',
  'n52Ring',
  'n53Ring',
  'n54Ring',
  'n55Ring',
  'n56Ring',
  'n57Ring',
  'n58Ring',
  'n59Ring',
  'n60Ring',
  'n61Ring',
  'n62Ring',
  'n63Ring',
  'n64Ring',
  'n65Ring',
  'n66Ring',
  'n67Ring',
  'n68Ring',
  'n69Ring',
  'n70Ring',
  'n71Ring',
  'n72Ring',
  'n73Ring',
  'n74Ring',
  'n75Ring',
  'n76Ring',
  'n77Ring',
  'n78Ring',
  'n79Ring',
  'n80Ring',
  'n81Ring',
  'n82

In [11]:
def get_all_descriptors(input_smile):
    # rdkit
    f,f_n = get_rdkit_descriptors(input_smile)
    
    #MACCS
    t_f,t_f_n = get_maccs(input_smile)
    f = np.concatenate([f,t_f])
    f_n += t_f_n
    
    #ECFP6
    t_f,t_f_n = get_ECFP6(input_smile)
    f = np.concatenate([f,t_f])
    f_n += t_f_n
    
    # MORDRED
    t_f,t_f_n = get_mordred(input_smile)
    f = np.concatenate([f,t_f])
    f_n += t_f_n
    
    return f, f_n

In [12]:
(a,b) = get_all_descriptors(tmp_smile)
print(a.shape)
print(len(b))

(4127,)
4127


In [13]:
param_json_path = 'data/params.json'
import json
with open(param_json_path) as json_file:
    param_dict = json.load(json_file)

In [14]:
### get all inchi paths and combine
import pandas as pd
all_data = None
for key in param_dict.keys():
    if 'inchi' in key:
        print(key + ': ' + param_dict[key])
        cur_data = pd.read_csv(param_dict[key])
        if all_data is None:
            all_data = cur_data.copy()
        else:
            all_data = pd.concat([all_data,cur_data]) 
print(all_data.shape)

gdsc_inchi_path: data/gdsc_compound_inchi_smiles.csv
beat_inchi_path: data/beat_aml/beat_aml_inhibitor_inchi_smiles.csv
xenografts_inchi_path: data/lung_cancer_xenografts/xenografts_inhibitor_inchi_smiles.csv
ccle_inchi_path: data/ccle/ccle_inhibitor_inchi_smiles.csv
pancreas_inchi_path: data/organoid_pancreas/pancreas_inhibitor_inchi_smiles.csv
(528, 5)


In [15]:
all_data.head()

Unnamed: 0          inhibitor  \
0           0  (5Z)-7-Oxozeaenol   
1           1     5-Fluorouracil   
2           2           A-443654   
3           3           A-770041   
4           4            A-83-01   

                                               inchi  \
0  InChI=1S/C19H22O7/c1-11-5-3-7-14(20)18(23)15(2...   
1  InChI=1S/C4H3FN2O2/c5-2-1-6-4(9)7-3(2)8/h1H,(H...   
2  InChI=1S/C24H23N5O/c1-15-22-10-16(6-7-24(22)29...   
3  InChI=1S/C34H39N9O3/c1-21(44)41-14-16-42(17-15...   
4  InChI=1S/C25H19N5S/c1-17-8-7-13-23(27-17)24-21...   

                      inchikey  \
0  NEQZWEXWOFPKOT-BYRRXHGESA-N   
1  GHASVSINZRGABV-UHFFFAOYSA-N   
2  YWTBGJGMTBHQTM-IBGZPJMESA-N   
3  ZMNWFTYYYCSSTF-UHFFFAOYSA-N   
4  HIJMSZGHKQPPJS-UHFFFAOYSA-N   

                                    canonical_smiles  
0  CC1CC=CC(=O)C(C(CC=CC2=C(C(=CC(=C2)OC)O)C(=O)O...  
1                               C1=C(C(=O)NC(=O)N1)F  
2  CC1=C2C=C(C=CC2=NN1)C3=CC(=CN=C3)OCC(CC4=CNC5=...  
3  CC(=O)N1CCN(CC1)C2CCC(CC2)N3C4=NC=NC(=C4C(=N3)...  
4  CC1=NC(=CC=C1)C2=NN(C=C2C3=CC=NC4=CC=CC=C34)C(...

In [16]:
from tqdm.notebook import tqdm
smiles = list(all_data['canonical_smiles'])
names = list(all_data['inhibitor'])
use_names_set = set()
use_smiles = []
use_names = []
features   = []
error_smiles = []
error_names = []
use_ids = []
for i in tqdm(np.arange(len(smiles))):
    try:
        cur_smiles = smiles[i]
        cur_name = names[i]
        if cur_name in use_names_set:
            continue
        (a,b) = get_all_descriptors(cur_smiles)
        use_names_set.add(cur_name)
        use_smiles.append(cur_smiles)
        use_names.append(cur_name)
        features.append(a)
        use_ids.append(i)
    except:
        error_smiles.append(cur_smiles)
        error_names.append(cur_name)
feature_names = b

/usr/local/apps/tensorflow_anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:87: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/apps/tensorflow_anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:87: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/apps/tensorflow_anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:87: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/apps/tensorflow_anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:87: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/apps/tensorflow_anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:87: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwa

In [23]:
cur_id = np.where(np.array(list(all_data['inhibitor'])) == '17-AAG (Tanespimycin)')[0]
get_all_descriptors(smiles[cur_id[0]])
print(cur_id)

[345]


In [24]:
'17-AAG (Tanespimycin)' in use_names#list(all_data['inhibitor'])

True

In [25]:
feature_matrix = np.array(features,dtype=np.float32)
out_df = pd.DataFrame({'canonical_smiles':use_smiles,
                       'inhibitor':use_names})
for i in range(len(feature_names)):
    feat = feature_names[i]
    out_df[feat] = feature_matrix[:,i]

In [26]:
out_df.head()

canonical_smiles          inhibitor  \
0  CC1CC=CC(=O)C(C(CC=CC2=C(C(=CC(=C2)OC)O)C(=O)O...  (5Z)-7-Oxozeaenol   
1                               C1=C(C(=O)NC(=O)N1)F     5-Fluorouracil   
2  CC1=C2C=C(C=CC2=NN1)C3=CC(=CN=C3)OCC(CC4=CNC5=...           A-443654   
3  CC(=O)N1CCN(CC1)C2CCC(CC2)N3C4=NC=NC(=C4C(=N3)...           A-770041   
4  CC1=NC(=CC=C1)C2=NN(C=C2C3=CC=NC4=CC=CC=C34)C(...            A-83-01   

   MaxEStateIndex  MinEStateIndex  MaxAbsEStateIndex  MinAbsEStateIndex  \
0       12.449593       -1.546408          12.449593           0.024198   
1       11.984815       -1.001157          11.984815           0.707037   
2        6.350272       -0.113155           6.350272           0.113155   
3       13.336040       -0.228281          13.336040           0.156382   
4        5.653641        0.490477           5.653641           0.490477   

        qed       MolWt  HeavyAtomMolWt  ExactMolWt  ...          MW  \
0  0.650373  362.377991      340.201996  362.136566  ...  362.136566   
1  0.482565  130.078003      127.054001  130.017853  ...  130.017853   
2  0.396777  397.481995      374.298004  397.190247  ...  397.190247   
3  0.283438  621.745972      582.434021  621.317566  ...  621.317566   
4  0.378026  421.528992      402.377014  421.136108  ...  421.136108   

         AMW   WPath  WPol  Zagreb1  Zagreb2   mZagreb1  mZagreb2  nSugars  \
0   7.544511  1581.0  43.0    128.0    147.0  10.500000  5.888889      0.0   
1  10.834822    84.0  10.0     42.0     46.0   4.083333  2.027778      0.0   
2   7.494156  2845.0  46.0    164.0    195.0   7.611111  6.472222      0.0   
3   7.309618  8753.0  83.0    256.0    312.0  13.500000  9.944445      0.0   
4   8.422722  2603.0  50.0    168.0    200.0   7.861111  6.750000      0.0   

   core_ester  
0         1.0  
1         0.0  
2         0.0  
3         0.0  
4         0.0  

[5 rows x 4074 columns]

In [27]:
out_df.shape

(389, 4074)

In [28]:
out_df.to_csv('data/molecure_descriptors.tsv',sep='\t',index=None)